### ISSUE TITLE
Revamp basic auth

### ISSUE THREAD

**Issue by AmrSaber** [AmrSaber/redirector#3]
Basic auth is too basic, it needs revamping.

I think the following configuration would be better:
```yaml
auth:
  basic-auth:
    my-auth:
      realm: SomeRealm # Defaults to "Restricted"
      users:
        - username: user-1
          password: 1234
        - username: user-2
          password: 5678

redirects:
  - from: some.where.com
    to: https://another.place.net
    auth:
      - my-auth
```

This will:
- Allow several users per auth configuration
- Allow multiple auth configuration to easily add/remove users or a group of users
- Be more extendable to more auth types in the future (maybe someday we can support OpenIDConnect)
